// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cW9XxigeNGDYT9xz35sevaH5tm6n6mc',
    appId: '1:843133914134:web:b8736539ac00e771427937',
    messagingSenderId: '843133914134',
    projectId: 'finalproject-c6869',
    authDomain: 'finalproject-c6869.firebaseapp.com',
    storageBucket: 'finalproject-c6869.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4BlHfLlUxYmhSgwsxkkLzl5H4yKqCO0',
    appId: '1:843133914134:android:f6a56f7ef8a3cbc4427937',
    messagingSenderId: '843133914134',
    projectId: 'finalproject-c6869',
    storageBucket: 'finalproject-c6869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIO9kCYmGFdsZUai2MfdUuZ9kgOS-J1Vc',
    appId: '1:843133914134:ios:7e08359e5b764873427937',
    messagingSenderId: '843133914134',
    projectId: 'finalproject-c6869',
    storageBucket: 'finalproject-c6869.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIO9kCYmGFdsZUai2MfdUuZ9kgOS-J1Vc',
    appId: '1:843133914134:ios:7e08359e5b764873427937',
    messagingSenderId: '843133914134',
    projectId: 'finalproject-c6869',
    storageBucket: 'finalproject-c6869.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1cW9XxigeNGDYT9xz35sevaH5tm6n6mc',
    appId: '1:843133914134:web:fce79a0264d6033b427937',
    messagingSenderId: '843133914134',
    projectId: 'finalproject-c6869',
    authDomain: 'finalproject-c6869.firebaseapp.com',
    storageBucket: 'finalproject-c6869.firebasestorage.app',
  );
}
